// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcp_connectTcpconnEventT struct {
	_      structs.HostLayout
	Pid    uint32
	Ppid   uint32
	Uid    uint32
	Comm   [16]int8
	Daddr  uint32
	Saddr  uint32
	Dport  uint16
	Sport  uint16
	Family uint16
	_      [2]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcp_connectMapEvents              = "events"
	tcp_connectProgHandleTcpconnect   = "handle_tcpconnect"
	tcp_connectVarUnusedTcpconnEventT = "unused_tcpconn_event_t"
)

// loadTcp_connect returns the embedded CollectionSpec for tcp_connect.
func loadTcp_connect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Tcp_connectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcp_connect: %w", err)
	}

	return spec, err
}

// loadTcp_connectObjects loads tcp_connect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcp_connectObjects
//	*tcp_connectPrograms
//	*tcp_connectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcp_connectObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcp_connect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcp_connectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_connectSpecs struct {
	tcp_connectProgramSpecs
	tcp_connectMapSpecs
	tcp_connectVariableSpecs
}

// tcp_connectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_connectProgramSpecs struct {
	HandleTcpconnect *ebpf.ProgramSpec `ebpf:"handle_tcpconnect"`
}

// tcp_connectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_connectMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// tcp_connectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcp_connectVariableSpecs struct {
	UnusedTcpconnEventT *ebpf.VariableSpec `ebpf:"unused_tcpconn_event_t"`
}

// tcp_connectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcp_connectObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_connectObjects struct {
	tcp_connectPrograms
	tcp_connectMaps
	tcp_connectVariables
}

func (o *tcp_connectObjects) Close() error {
	return _Tcp_connectClose(
		&o.tcp_connectPrograms,
		&o.tcp_connectMaps,
	)
}

// tcp_connectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcp_connectObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_connectMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *tcp_connectMaps) Close() error {
	return _Tcp_connectClose(
		m.Events,
	)
}

// tcp_connectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcp_connectObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_connectVariables struct {
	UnusedTcpconnEventT *ebpf.Variable `ebpf:"unused_tcpconn_event_t"`
}

// tcp_connectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcp_connectObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcp_connectPrograms struct {
	HandleTcpconnect *ebpf.Program `ebpf:"handle_tcpconnect"`
}

func (p *tcp_connectPrograms) Close() error {
	return _Tcp_connectClose(
		p.HandleTcpconnect,
	)
}

func _Tcp_connectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcp_connect_x86_bpfel.o
var _Tcp_connectBytes []byte
